<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuoteItemSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('quote_items')->insert([
            // Items para COT-2024-001 (Carlos Pérez - Evento familiar)
            [
                'quote_id' => 1,
                'item_type' => 'product',
                'product_id' => 1,
                'name' => 'Tequeños',
                'description' => 'Deliciosos tequeños de queso blanco (porción de 6 unidades)',
                'unit' => 'pcs',
                'quantity' => 2.000,
                'unit_price' => 15.00,
                'discount_percentage' => 5.00,
                'discount_amount' => 1.50,
                'tax_percentage' => 16.00,
                'tax_amount' => 4.56,
                'subtotal' => 30.00,
                'total' => 33.06,
                'sort_order' => 1,
                'metadata' => json_encode(['observaciones' => 'Sin salsa picante']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'quote_id' => 1,
                'item_type' => 'product',
                'product_id' => 2,
                'name' => 'Pabellón Criollo',
                'description' => 'Plato típico venezolano: carne mechada, caraotas negras, arroz blanco y tajadas',
                'unit' => 'pcs',
                'quantity' => 1.000,
                'unit_price' => 35.00,
                'discount_percentage' => 5.00,
                'discount_amount' => 1.75,
                'tax_percentage' => 16.00,
                'tax_amount' => 5.32,
                'subtotal' => 35.00,
                'total' => 38.57,
                'sort_order' => 2,
                'metadata' => json_encode(['observaciones' => 'Carne bien cocida']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'quote_id' => 1,
                'item_type' => 'product',
                'product_id' => 5,
                'name' => 'Jugo Natural',
                'description' => 'Jugo natural de frutas de temporada',
                'unit' => 'pcs',
                'quantity' => 3.000,
                'unit_price' => 8.00,
                'discount_percentage' => 0.00,
                'discount_amount' => 0.00,
                'tax_percentage' => 0.00,
                'tax_amount' => 0.00,
                'subtotal' => 24.00,
                'total' => 24.00,
                'sort_order' => 3,
                'metadata' => json_encode(['sabores' => ['naranja', 'guayaba', 'parchita']]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Items para COT-2024-002 (Empresa ABC - Catering empresarial)
            [
                'quote_id' => 2,
                'item_type' => 'product',
                'product_id' => 1,
                'name' => 'Tequeños',
                'description' => 'Deliciosos tequeños de queso blanco (porción de 6 unidades)',
                'unit' => 'pcs',
                'quantity' => 10.000,
                'unit_price' => 15.00,
                'discount_percentage' => 5.00,
                'discount_amount' => 7.50,
                'tax_percentage' => 16.00,
                'tax_amount' => 22.80,
                'subtotal' => 150.00,
                'total' => 165.30,
                'sort_order' => 1,
                'metadata' => json_encode(['catering' => true]),
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'quote_id' => 2,
                'item_type' => 'product',
                'product_id' => 3,
                'name' => 'Arepa Reina Pepiada',
                'description' => 'Arepa de maíz rellena con ensalada de pollo y aguacate',
                'unit' => 'pcs',
                'quantity' => 8.000,
                'unit_price' => 18.00,
                'discount_percentage' => 5.00,
                'discount_amount' => 7.20,
                'tax_percentage' => 16.00,
                'tax_amount' => 21.89,
                'subtotal' => 144.00,
                'total' => 158.69,
                'sort_order' => 2,
                'metadata' => json_encode(['catering' => true]),
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'quote_id' => 2,
                'item_type' => 'service',
                'product_id' => null,
                'name' => 'Servicio de Montaje',
                'description' => 'Servicio completo de montaje y desmontaje para evento',
                'unit' => 'servicio',
                'quantity' => 1.000,
                'unit_price' => 50.00,
                'discount_percentage' => 10.00,
                'discount_amount' => 5.00,
                'tax_percentage' => 16.00,
                'tax_amount' => 7.20,
                'subtotal' => 50.00,
                'total' => 52.20,
                'sort_order' => 3,
                'metadata' => json_encode(['incluye' => ['mesas', 'sillas', 'mantelería']]),
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],

            // Items para COT-2024-003 (María López - Pedido semanal panadería)
            [
                'quote_id' => 3,
                'item_type' => 'product',
                'product_id' => 7,
                'name' => 'Pan Integral',
                'description' => 'Pan integral con semillas de ajonjolí y girasol',
                'unit' => 'pcs',
                'quantity' => 20.000,
                'unit_price' => 4.00,
                'discount_percentage' => 5.00,
                'discount_amount' => 4.00,
                'tax_percentage' => 16.00,
                'tax_amount' => 12.80,
                'subtotal' => 80.00,
                'total' => 88.80,
                'sort_order' => 1,
                'metadata' => json_encode(['pedido_semanal' => true]),
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subDays(1),
            ],
            [
                'quote_id' => 3,
                'item_type' => 'product',
                'product_id' => 9,
                'name' => 'Galletas de Avena',
                'description' => 'Galletas caseras de avena con pasas (paquete de 12 unidades)',
                'unit' => 'paquetes',
                'quantity' => 4.000,
                'unit_price' => 10.00,
                'discount_percentage' => 5.00,
                'discount_amount' => 2.00,
                'tax_percentage' => 16.00,
                'tax_amount' => 6.40,
                'subtotal' => 40.00,
                'total' => 44.40,
                'sort_order' => 2,
                'metadata' => json_encode(['pedido_semanal' => true]),
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subDays(1),
            ],

            // Items para COT-2024-004 (Roberto Silva - Desayunos corporativos)
            [
                'quote_id' => 4,
                'item_type' => 'product',
                'product_id' => 11,
                'name' => 'Cappuccino',
                'description' => 'Cappuccino con espuma de leche cremosa y canela',
                'unit' => 'pcs',
                'quantity' => 5.000,
                'unit_price' => 9.00,
                'discount_percentage' => 0.00,
                'discount_amount' => 0.00,
                'tax_percentage' => 16.00,
                'tax_amount' => 7.20,
                'subtotal' => 45.00,
                'total' => 52.20,
                'sort_order' => 1,
                'metadata' => json_encode(['desayuno_corporativo' => true]),
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
            [
                'quote_id' => 4,
                'item_type' => 'product',
                'product_id' => 12,
                'name' => 'Sandwich Club',
                'description' => 'Sandwich club house con jamón, queso, tomate, lechuga y papas fritas',
                'unit' => 'pcs',
                'quantity' => 2.000,
                'unit_price' => 22.00,
                'discount_percentage' => 0.00,
                'discount_amount' => 0.00,
                'tax_percentage' => 16.00,
                'tax_amount' => 7.04,
                'subtotal' => 44.00,
                'total' => 51.04,
                'sort_order' => 2,
                'metadata' => json_encode(['desayuno_corporativo' => true]),
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],

            // Items para COT-2024-005 (Elena Ramírez - Cliente nuevo)
            [
                'quote_id' => 5,
                'item_type' => 'product',
                'product_id' => 3,
                'name' => 'Arepa Reina Pepiada',
                'description' => 'Arepa de maíz rellena con ensalada de pollo y aguacate',
                'unit' => 'pcs',
                'quantity' => 2.000,
                'unit_price' => 18.00,
                'discount_percentage' => 5.00,
                'discount_amount' => 1.80,
                'tax_percentage' => 16.00,
                'tax_amount' => 5.47,
                'subtotal' => 36.00,
                'total' => 39.67,
                'sort_order' => 1,
                'metadata' => json_encode(['cliente_nuevo' => true]),
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(10),
            ],
            [
                'quote_id' => 5,
                'item_type' => 'product',
                'product_id' => 4,
                'name' => 'Quesillo',
                'description' => 'Postre tradicional venezolano tipo flan de caramelo',
                'unit' => 'pcs',
                'quantity' => 1.000,
                'unit_price' => 12.00,
                'discount_percentage' => 2.50,
                'discount_amount' => 0.30,
                'tax_percentage' => 16.00,
                'tax_amount' => 1.87,
                'subtotal' => 12.00,
                'total' => 13.57,
                'sort_order' => 2,
                'metadata' => json_encode(['cliente_nuevo' => true]),
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(10),
            ],
        ]);
    }
}